### ISSUE TITLE
Should DropwizardJdbi2DaoExtension/DropwizardJdbi2Extension call handle.begin() in beforeEach?

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi-test#127]
In `DropwizardJdbi2DaoExtension` and `DropwizardJdbi2Extension` we call `configureDBI` in the constructor, which sets the `autoCommit` on the Handle's `Connection` to `false`. I am not sure why I did it this way all those years ago, instead of just calling `handle.begin()` in a `@BeforeEach` method, which is what the JDBI 3 extensions do. Looking at the code for both JDBI 2 and JDBI 3, the `Handle#begin()` method calls `TransactionHandler#begin(Handle)` which has multiple implementations. Both JDBI 2 and 3 have a `LocalTransactionHandler` which does set `autoCommit` to false on the underlying `Connection`.

Since the tests will use that handler, I think it's perfectly safe to use `handle.begin()` but would we then want to change the `configureDBI` implementation? Or should we just leave it all alone since it has worked like this for literally years?

**Comment by chrisrohr** [comment]
I would say whatever is easier.  Isn’t JDBI 2 end of life anyways?  I don’t think we should put too much effort into an older version of a technology.

**Comment by sleberknight** [comment]
OK, then I will close this as "Won't Fix"
